### ISSUE TITLE
Doesn't appear to work on Watch

### ISSUE THREAD

**Issue by taijuten** [1337programming/webpack-shell-plugin#10]
This appears to work on webpack start, but I'm having issues getting it to work on the actual build triggered by `watch`.

Using:

- `webpack-shell-plugin 0.4.2`
- `webpack 1.13.1`

Any thoughts?

**Comment by opiepj** [comment]
Interesting I would have to test this out.

**Comment by opiepj** [comment]
I'm unable to replicate, how are you using the plugin?

**Comment by flyon** [comment]
I was also expecting this to work by default and find the standard dev option (= run only once) confusing. Turning it off did what I expected. What is the usecase for the default (run only once) when watch is true?
