### ISSUE TITLE
beforeBuildStart

### ISSUE THREAD

**Issue by tomekwi** [1337programming/webpack-shell-plugin#11]
Hello,

I have an unusual setup – at the moment the only available way to build part of my app is to output it into a file via a shell command. After that, I have to read that output from disk and use it in my webpack build.

Would it be possible to execute a command before my build starts? How about adding a `beforeBuildStart` config option for that?

**Comment by alexholt** [comment]
No need for a `beforeBuildStart`. I just switched it to use the sync exec and `onBuildStart` is now able to create files I then use in the build.

**Comment by tomekwi** [comment]
Yeah 👍 , was thinking about that as well. I thought maybe `onBuildStart` is intended to run in parallel.

**Comment by opiepj** [comment]
Hey guys I appreciate the feedback. 

Just a few comments:
@alexholt This solution proposed works if you are using beforeBuildStart. However it will break for other cases.

@tomekwi If you need a task to execute before webpack build why not use an npm script or something like: `npm run myTask && npm run webpack`.

The shell plugin should only be concerned about the webpack compile time and not the entire devops process.

**Comment by tomekwi** [comment]
@opiepj When I’m running webpack-dev-server, I want `beforeBuildStart` to run every time a webpack build gets triggered (i. e. every time I change a file). Not before I start the server. That’s what drew me to this package in the first place.

**Comment by flyon** [comment]
Agreed, npm run actions are nice but Im trying to have only one process running in watch mode. I want to do something before and after every time webpacks watch mode is triggered.
