### ISSUE TITLE
propagate stdout stderr for commands that not exit

### ISSUE THREAD

**Issue by bjrmatos** [1337programming/webpack-shell-plugin#13]
hi!, i have a command that doesn't exit (it is a watcher of files) so this plugin never tell me the output of the command. i have easily solved that by doing:

```js
var proc = exec(script, puts);
proc.stdout.pipe(process.stdout);
proc.stderr.pipe(process.stdout);
```
demo:
![webpack-shell](https://cloud.githubusercontent.com/assets/4262050/17641539/d6f0c496-60e9-11e6-9f89-929efe3a4e3e.gif)

would you be insterested in a PR?

**Comment by opiepj** [comment]
Yes definitely feel free to make a PR

**Comment by bjrmatos** [comment]
done! :smile:

**Comment by opiepj** [comment]
#14 Merged thank you for the help!
