### ISSUE TITLE
Exit codes ignored

### ISSUE THREAD

**Issue by gvandegrift** [1337programming/webpack-shell-plugin#16]
Hi,

I am running a process that I would like to fail the npm build process if my spawned process fails (i.e., non-zero exit code).  There doesn't appear to be a way to do that.  Have you considered this?  Would you be open to a PR?

Geoff

**Comment by opiepj** [comment]
I would be open to a PR. However could this behavior be toggled?

**Comment by gvandegrift** [comment]
Yes.  My intent would be to include a config option like "throwOnNonZeroExitCode" or something like that.

**Comment by DarkXaHTeP** [comment]
This pull request seems to be open for a long time. Is there a plan to merge it?

**Comment by opiepj** [comment]
Sent up

**Comment by Billy-** [comment]
This does not appear to have been documented
