### ISSUE TITLE
Unable to use curly braces and quotes

### ISSUE THREAD

**Issue by a-koka** [1337programming/webpack-shell-plugin#21]
I'm using this plugin to generate a JSON file with my app version like below:

```
new WebpackShellPlugin({onBuildEnd:['cat package.json | grep version | sed -e \'s/[",]//\'g | sed -e \'s/.*: \(.*\)/{\"version\": \"\1\"}/\' > build/app-info.json']})
```

This shell command works perfectly when run in the terminal but when generated via WebPack, the JSON file is missing the curly braces and the double quotes. Is there any way to get around this?

Thank you!

**Comment by opiepj** [comment]
I would just have it execute some script or patch file and pass arguments to it. The shell plugin is to just do minor shell commands, anything more probably should be handled in a task management script.

**Comment by a-koka** [comment]
Makes sense. Thanks!
