### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by jamiewinder** [1337programming/webpack-shell-plugin#23]
I'm not sure when this started, but after recently updating webpack-shell-plugin to 0.4.6, my config seems to have stopped working. I have the following in my Webpack 2.1.0-beta.27 config:
```js
    plugins: [
        new WebpackShellPlugin({
            onBuildEnd: ['tsc --d --declarationDir dist/typings'],
            dev: false
        })
    ]
```
Which, when I try to run Webpack gives me:
```bash
Executing post-build scripts
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn tsc ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
I'm not 100% sure what versions are affected, but I rolled back to version 0.4.3 of this plugin, and that seemed to do the trick.

**Comment by opiepj** [comment]
Revert back to 0.4.3, let me see what's the issue

**Comment by opiepj** [comment]
What operating system are you using?

**Comment by opiepj** [comment]
Could you try using 0.4.7?

**Comment by jamiewinder** [comment]
Thanks. To be clear, 0.4.3 works fine so there's nothing to share from that version. I've tried 0.4.7, and now I get a different error?

```
Executing post-build scripts
\webpack-shell-plugin\lib\index.js:196
        this.spreadStdoutAndStdErr(exec(script, puts));
                                                ^

ReferenceError: puts is not defined
    at WebpackShellPlugin.handleScript (\node_modules\webpack-shell-plugin\lib\index.js:196:49)
    at Compiler.<anonymous> (\node_modules\webpack-shell-plugin\lib\index.js:254:19)
```

I'm on Windows 8 64-Bit

**Comment by opiepj** [comment]
@szymonkudzia made that fix #24 

Try updating your module again.

**Comment by gvandegrift** [comment]
0.4.8 works for me (and throws on failure 😄 ).  Thanks!

**Comment by jamiewinder** [comment]
Seems to be working fine now, thanks!

**Comment by opiepj** [comment]
Thanks everyone
