### ISSUE TITLE
onBuildEnd is using webpack 'emit' but should use 'after-emit'

### ISSUE THREAD

**Issue by kmashint** [1337programming/webpack-shell-plugin#25]
The webpack-shell-plugin docs indicate onBuildEnd should be "after files are emitted" ...

onBuildEnd: array of scripts to execute after files are emitted at the end of the compilation. Default: [ ]

... but it uses 'emit' rather than 'after-emit' and we've observed problems due to this where the commands run before the files are actually available since the emit routines are async.

`compiler.plugin('emit', function (compilation, callback) ...`

webpack docs https://webpack.github.io/docs/plugins.html indicate 'after-emit' is the desired event:

emit(c: Compilation) async
    The Compiler begins with emitting the generated assets. Here plugins have the last chance to add assets to the c.assets array.

after-emit(c: Compilation) async
    The Compiler has emitted all assets.

**Comment by opiepj** [comment]
Done, Thank you @kmashint.
