### ISSUE TITLE
0.4.4 → 0.4.5 breaks pipe operator `|`

### ISSUE THREAD

**Issue by rkaw92** [1337programming/webpack-shell-plugin#27]
Hi, our builds containing the following command just stopped working after npm automatically pulled in version `0.4.9` today.
```js
		new WebpackShellPlugin({
			onBuildStart: [
				'git describe --tags HEAD >.app-version || date --rfc-3339=seconds >.app-version'
			]
		}),
```

The last good version that runs it is `0.4.4`. In `0.4.5`, we get this error, but it does **not stop the build**:
```
error: unknown option `rfc-3339=seconds'
usage: git describe [options] <commit-ish>*
  [...] git usage info here [...]
Error:  129 undefined
  [...] webpack result, all green [...]
```

In `0.4.6`, on the other hand, the error is actually thrown and webpack bails out (with `--bail`):
```
.../node_modules/webpack-shell-plugin/lib/index.js:156
    throw error;
    ^
129
```

(Not sure what the actual command being run is, but I would wager it's just git with appended arguments but with the pipeline character skipped.)

This behaviour continues up to the current newest version, `0.4.9`.
It seems that some parsing behaviour has dramatically changed between 0.4.4 and 0.4.5 and broken using proper shell constructs.

**Comment by opiepj** [comment]
We have changed the execution process from process.exec to process.spawn in 0.4.5. I'm sure it has to do with how we are serializing the spawn script.

Right now we are doing:
```js
let spawn = require('process').spawn;
  serializeScript(script) {
    if (typeof script === 'string') {
      const [command, ...args] = script.split(' ');
      return {command, args};
    }
    const {command, args} = script;
    return {command, args};
  }
const {command, args} = this.serializeScript(script);
spawn(command, args, {stdio: 'inherit'});
```
We need to modify this and support various shell constructs. Or we can just switch back to process.exec.

**Comment by rkaw92** [comment]
Not really sure if parsing the shell is a good idea - it's utterly impossible using regexp and error-prone even if using a proper parser. Is there a reason why this package needs to serialize commands?

**Comment by opiepj** [comment]
We switched to spawn to resolve #20 and #17. For the spawn process you need to serialize the script. Maybe we can revert back to exec and find a way to retain colors like [this](http://stackoverflow.com/questions/18825493/retaining-output-colors-when-shelling-out-to-node). I think I will work on getting that out.

**Comment by opiepj** [comment]
So I tried several things, but I just couldn't give up using spawn. I tried optimizing it a bit, but I don't think it will solve your issue.

Though #28 won't fix your case, I did add a setting called **`safe`** which will execute the script in a the previous exec process - this should work for you.

You will need to turn on the setting:
```js
new WebpackShellPlugin({onBuildStart:['echo "Webpack Start"'], onBuildEnd:['echo "Webpack End"'], safe: true});
``` 

Let me know if that works.

**Comment by opiepj** [comment]
@rkaw92 any updates? Does this work for you?

**Comment by rkaw92** [comment]
Sorry, I haven't checked with our build just yet. Will post an update Friday when I can get on it.

Dnia 15 grudnia 2016 02:02:55 CET, Patrick Opie <notifications@github.com> napisał(a):
>@rkaw92 any updates? Does this work for you?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/1337programming/webpack-shell-plugin/issues/27#issuecomment-267205910

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeffbski** [comment]
Yeah, I ran into issues too both with the pipe and with >, but adding the safe: true allows it to work again.

Since this type of change breaks old behavior (now we have to add the safe option) it probably should have been signaled as a breaking change so people wouldn't be caught off guard, but maybe that's why you did the recent bump to 0.5.0. It might not have been obvious that it was breaking I suppose.

**Comment by rkaw92** [comment]
@opiepj 0.5.0's `safe` option does indeed solve the issue. Thanks.
