### ISSUE TITLE
Platform specific scritps

### ISSUE THREAD

**Issue by a-koka** [1337programming/webpack-shell-plugin#30]
I realize that this has been an open point of discussion in regards to `npm`. Do you have any recommendations for how one should go about having a script run only on Windows or Mac?

**Comment by opiepj** [comment]
typically you should avoid OS specific operation, but if you have to you could setup your node script to utilize the [OS module](https://nodejs.org/api/os.html). You could do the same with Python, Go, or w/e

**Comment by a-koka** [comment]
I should have been more specific in my original question. I have a shell script which runs upon `onBuildEnd`. I realize that one could use `Perl`, `Python` etc. to solve this but wondering if there is a way to run the shell script on linux bases systems only.

**Comment by opiepj** [comment]
Don't rely on this wrapper, it will become a bottleneck for you even if it supported that capability. Your best best is to just build out the script and execute it through the plugin:
```js
// Node example
let os = require('os');
if (os.platform() === 'linux') {
  // Do something
}
```

The capability you're describing would be out of scope for this plugin.
