### ISSUE TITLE
Doesn't work with webpack --watch

### ISSUE THREAD

**Issue by johnborges** [1337programming/webpack-shell-plugin#31]
Doesn't seem work with `webpack --watch`. Build runs, but my shell commands aren't. Has anyone tried this with `--watch`?

**Comment by opiepj** [comment]
Can you share me your setup?

**Comment by zappee** [comment]
Same issue. I cannot use this plugin because it does not work as described and expected.
After start webpack onBuildStart, onBuildEnd and onBuildExit are executed. If I modify any js file then onBuildExit is executed BUT BEFORE (and not AFTER) webpack finished.

**My config:**
```
    plugins: [
        new WebpackShellPlugin({
	    onBuildStart: ['echo -e \n--> Webpack is running...'],
	    onBuildExit: ['echo abcccc'],
	    onBuildEnd:['echo -e --> Finished\n\n']
	})
    ]
```

**command:**
`webpack --progress --colors --bail --watch`

**Output:**
```
Executing pre-build scripts

--> Webpack is running...
 95% emitExecuting post-build scripts
--> Finished


Executing additional scripts before exit
abcccc
Hash: b4c3e22ed10fdddc9900
Version: webpack 1.14.0
Time: 3445ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.45 MB       0  [emitted]  main
    + 507 hidden modules
 95% emitExecuting additional scripts before exit
abcccc
Hash: 6f718eda48c1715b4760
Version: webpack 1.14.0
Time: 452ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.45 MB       0  [emitted]  main
    + 507 hidden modules



 95% emitExecuting additional scripts before exit
abcccc
Hash: 1f3383c679eddd3c261d
Version: webpack 1.14.0
Time: 436ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.45 MB       0  [emitted]  main
    + 507 hidden modules

```

**Comment by zappee** [comment]
I need to access to the bundle files. I think you need to use after-emit, since emit is triggered when Webpack starts emitting the files.

**Comment by zappee** [comment]
Okay, I could see the source code.
This plugin works properly!

If you need to access to the bundle file then you need to use onBuildExit.

**Comment by opiepj** [comment]
Keeping this issue open. Need to readvise this pattern.
