### ISSUE TITLE
Run multiple commands

### ISSUE THREAD

**Issue by mjhamm75** [1337programming/webpack-shell-plugin#33]
I am trying to run multiple commands and get 

```
internal/child_process.js:289
  var err = this._handle.spawn(options);
                         ^

TypeError: Bad argument
```

I am trying to run in the `onBuildEnd` with a command that does this
`'cp -R src/main/webapp/build/ target/lcrf-web-CUBS-SNAPSHOT/build/ && echo "copy finished" '`
Is there a way that I can do this with this plugin?

**Comment by opiepj** [comment]
Try setting safe to true

**Comment by mjhamm75** [comment]
That fixed the issue.
