### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [1337programming/webpack-shell-plugin#70]
Hi, what is the current status of this project? Is it still actively maintained or are you looking for maintainers?

**Comment by mikeerickson** [comment]
I won’t use the word abandoned, but definitely say it is not a priority.

**Comment by DanielRuf** [comment]
Hi @mikeerickson, how exactly are you related to this project? Because you have no member, collaborator or contributor info in your comment header.

**Comment by mikeerickson** [comment]
Easy buddy, just offering my observation. Relax my friend, it is Saturday after all.

**Comment by DanielRuf** [comment]
I was just curious ;-)

**Comment by keemor** [comment]
I moved to [https://github.com/s00d/webpack-shell-plugin-next](https://github.com/s00d/webpack-shell-plugin-next) to fix [Tapable.plugin is deprecated](https://github.com/1337programming/webpack-shell-plugin/issues/61)
